version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=projeto-cloud
      - MYSQL_USER=mateuscarestiato
      - MYSQL_PASSWORD=@mateus123
    ports:
      - "3301:3306"
    volumes:
      - /c/volumes/mysql_data:/var/lib/mysql    
  app:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/projeto-cloud
      - SPRING_DATASOURCE_USERNAME=mateuscarestiato
      - SPRING_DATASOURCE_PASSWORD=@mateus123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      
    
