name: Build and deploy JAR app to Azure Web App - projeto-cloud-ibmec

on:
  push:
    branches:
      - main
      - feature/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Find and verify JAR file
        id: find-jar
        run: |
          echo "Looking for JAR files:"
          find . -name "*.jar" -type f
          JAR_FILE=$(find ./target -name "*.jar" -type f | grep -v original | head -n 1)
          if [ -n "$JAR_FILE" ]; then
            echo "Found JAR file: $JAR_FILE"
            echo "jar_file=$JAR_FILE" >> $GITHUB_OUTPUT
            # Verify it's a proper Spring Boot JAR
            if [ -s "$JAR_FILE" ]; then
              echo "JAR file size: $(stat -c%s "$JAR_FILE") bytes"
            else
              echo "WARNING: JAR file is empty!"
            fi
          else
            echo "ERROR: No JAR file found in target directory!"
            exit 1
          fi

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: ${{ steps.find-jar.outputs.jar_file }}
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: List downloaded files
        run: |
          echo "Downloaded files:"
          ls -la
          # Rename the JAR to app.jar for consistency
          JAR_FILE=$(ls *.jar | head -n 1)
          if [ -n "$JAR_FILE" ]; then
            mv "$JAR_FILE" app.jar
            echo "Renamed $JAR_FILE to app.jar"
            echo "Final file size: $(stat -c%s app.jar) bytes"
          fi

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E3642754D42847BB94F31BDD9CB57C88 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F0F6D7E05BC943B7902C85536A6847EB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D05525DEEF014FA8B7281549D45A2506 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'projeto-cloud-ibmec'
          slot-name: 'Production'
          package: 'app.jar'