name: Build and deploy Docker app to Azure Web App - projeto-cloud-ibmec

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Verify JAR file
        run: |
          echo "Checking target directory:"
          ls -la target/
          JAR_FILE=$(find ./target -name "*.jar" -type f | grep -v original | head -n 1)
          if [ -n "$JAR_FILE" ]; then
            echo "Found JAR file: $JAR_FILE"
            echo "JAR file size: $(stat -c%s "$JAR_FILE") bytes"
          else
            echo "ERROR: No JAR file found!"
            exit 1
          fi

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ibmecdockerimage.azurecr.io
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        run: |
          # Build the Docker image
          docker build -t ibmec-trading-app:latest .
          
          # Tag for Azure Container Registry
          docker tag ibmec-trading-app:latest ibmecdockerimage.azurecr.io/ibmec-trading:latest
          
          # Push to Azure Container Registry
          docker push ibmecdockerimage.azurecr.io/ibmec-trading:latest
          
          echo "Docker image pushed successfully!"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E3642754D42847BB94F31BDD9CB57C88 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F0F6D7E05BC943B7902C85536A6847EB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D05525DEEF014FA8B7281549D45A2506 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'projeto-cloud-ibmec'
          slot-name: 'Production'
          images: 'ibmecdockerimage.azurecr.io/ibmec-trading:latest'