name: Build and deploy JAR app to Azure Web App - projeto-cloud

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Verify Maven
        run: mvn -version

      - name: Display project structure before build
        run: |
          pwd
          ls -la
          if [ -f "pom.xml" ]; then
            echo "pom.xml exists"
            cat pom.xml | grep -A 5 "<artifactId>"
          else
            echo "pom.xml not found!"
          fi

      - name: Build with Maven
        run: mvn clean package -DskipTests
      
      - name: Display project structure after build
        run: |
          ls -la
          echo "Contents of target directory:"
          if [ -d "target" ]; then
            ls -la target/
          else
            echo "target directory not found!"
          fi

      - name: Find JAR files
        run: find . -name "*.jar" -type f

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: $(find . -name "*.jar" -type f | head -n 1)
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Debug downloaded artifacts
        run: |
          pwd
          ls -la
          echo "Current directory size:"
          du -sh .
        
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_24E168FC0A43497CA06655E3EF0E3A0A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_36480AC1DF2F41619AA7E292F048A469 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E8B2BCD421094956A3D0D11027EE11BE }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'projeto-cloud'
          slot-name: 'Production'
          package: '*.jar'